

  
    
  


  





  

<!DOCTYPE html>
<html lang="en-us">
  <head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.49.2 with theme Tranquilpeak 0.4.3-BETA">
    <title>Working with Strings in R: Seattle Pet Names</title>
    <meta name="author" content="Hugo Toscano">
    <meta name="keywords" content="">

    <link rel="icon" href="../../../favicon.png">
    

    
    <meta name="description" content="Welcome to the blog. In this new post I’ll do a short tutorial on how to work with strings in R. I’ll show you some of the main functions of the stringr package and the amazing power of the rebus package. The data frame I will be using is from the week 13 of TidyTuesday. This data frame seemed to be the perfect opportunity to build this tutorial given the importance of strings for its understanding.">
    <meta property="og:description" content="Welcome to the blog. In this new post I’ll do a short tutorial on how to work with strings in R. I’ll show you some of the main functions of the stringr package and the amazing power of the rebus package. The data frame I will be using is from the week 13 of TidyTuesday. This data frame seemed to be the perfect opportunity to build this tutorial given the importance of strings for its understanding.">
    <meta property="og:type" content="blog">
    <meta property="og:title" content="Working with Strings in R: Seattle Pet Names">
    <meta property="og:url" content="/2019/04/working-with-strings-in-r-seattle-pet-names/">
    <meta property="og:site_name" content="Hugo Toscano">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Hugo Toscano">
    <meta name="twitter:description" content="Welcome to the blog. In this new post I’ll do a short tutorial on how to work with strings in R. I’ll show you some of the main functions of the stringr package and the amazing power of the rebus package. The data frame I will be using is from the week 13 of TidyTuesday. This data frame seemed to be the perfect opportunity to build this tutorial given the importance of strings for its understanding.">
    
    

    
    

    
      <meta property="og:image" content="https://res.cloudinary.com/dabczf7ag/image/upload/v1528704790/foto1.jpg">
    

    
    
    

    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="../../../css/style-jsjn0006wyhpyzivf6yceb31gvpjatbcs3qzjvlumobfnugccvobqwxnnaj8.min.css" />
    
    

    
      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-123-45', 'auto');
	
	ga('send', 'pageview');
}
</script>

    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="4">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="../../../">Hugo Toscano</a>
  </div>
  
    
      <a class="header-right-picture "
         href="../../../#about">
    
    
    
      
        <img class="header-picture" src="https://res.cloudinary.com/dabczf7ag/image/upload/v1528704790/foto1.jpg" alt="Author&#39;s picture" />
      
    
    </a>
  
</header>

      <nav id="sidebar" data-behavior="4">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="../../../#about">
          <img class="sidebar-profile-picture" src="https://res.cloudinary.com/dabczf7ag/image/upload/v1528704790/foto1.jpg" alt="Author&#39;s picture" />
        </a>
        <h4 class="sidebar-profile-name">Hugo Toscano</h4>
        
          <h5 class="sidebar-profile-bio">Contact: hugo_toscano@outlook.com</h5>
        
      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../">
    
      <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      
      <span class="sidebar-button-desc">Home</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../2018/07/about-me/">
    
      <i class="sidebar-button-icon fa fa-lg fa-user"></i>
      
      <span class="sidebar-button-desc">About me</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      
      <span class="sidebar-button-desc">Categories</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../tags">
    
      <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      
      <span class="sidebar-button-desc">Tags</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-search"></i>
      
      <span class="sidebar-button-desc">Archives</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://github.com/toscano84" target="_blank" rel="noopener">
    
      <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      
      <span class="sidebar-button-desc">GitHub</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://www.linkedin.com/in/hugo-toscano-56766a2a/" target="_blank" rel="noopener">
    
      <i class="sidebar-button-icon fa fa-lg fa-linkedin"></i>
      
      <span class="sidebar-button-desc">LinkedIn</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://twitter.com/htoscano84" target="_blank" rel="noopener">
    
      <i class="sidebar-button-icon fa fa-lg fa-twitter"></i>
      
      <span class="sidebar-button-desc">Twitter</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      

    </ul>
  </div>
</nav>

      

      <div id="main" data-behavior="4"
        class="
               hasCoverMetaIn
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
            <div class="post-header main-content-wrap text-left">
  
    <h1 class="post-title" itemprop="headline">
      Working with Strings in R: Seattle Pet Names
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2019-04-29T00:00:00Z">
        
  April 29, 2019

      </time>
    
    
  
  
    <span>in</span>
    
      <a class="category-link" href="../../../categories/tutorials">Tutorials</a>
    
  

  </div>

</div>
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              <p>Welcome to the blog. In this new post I’ll do a short tutorial on how to work with strings in R. I’ll show you some of the main functions of the <code>stringr</code> package and the amazing power of the <code>rebus</code> package. The data frame I will be using is from the week 13 of <a href="https://github.com/rfordatascience/tidytuesday">TidyTuesday</a>. This data frame seemed to be the perfect opportunity to build this tutorial given the importance of strings for its understanding. The data is called “Seattle Pet Names” and is related to the date, names, species, breed, and zip code of the pets registered in Seattle. I’ll be focusing the analyses on the names given to cats and dogs.</p>
<p>Let’s start the tutorial by loading the needed packages.</p>
<pre class="r"><code>library(tidyverse) # wrangling and data visualization
library(kableExtra) # visualize html tables
library(rebus) # string maniipulation
library(data.table) # in this case open dataframe
library(splitstackshape) # split columns
library(lubridate) # dealing with dates and times</code></pre>
<p>We now open the “Seattle Pet Names” file and <code>glimpse</code> it.</p>
<pre class="r"><code># open file
pet_names &lt;- fread(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-26/seattle_pets.csv&quot;)


# explore it
glimpse(pet_names)</code></pre>
<pre><code>## Observations: 52,519
## Variables: 7
## $ license_issue_date &lt;chr&gt; &quot;November 16 2018&quot;, &quot;November 11 2018&quot;, &quot;No...
## $ license_number     &lt;chr&gt; &quot;8002756&quot;, &quot;S124529&quot;, &quot;903793&quot;, &quot;824666&quot;, &quot;...
## $ animals_name       &lt;chr&gt; &quot;Wall-E&quot;, &quot;Andre&quot;, &quot;Mac&quot;, &quot;Melb&quot;, &quot;Gingersn...
## $ species            &lt;chr&gt; &quot;Dog&quot;, &quot;Dog&quot;, &quot;Dog&quot;, &quot;Cat&quot;, &quot;Cat&quot;, &quot;Dog&quot;, &quot;...
## $ primary_breed      &lt;chr&gt; &quot;Mixed Breed, Medium (up to 44 lbs fully gr...
## $ secondary_breed    &lt;chr&gt; &quot;Mix&quot;, &quot;Dachshund, Standard Wire Haired&quot;, N...
## $ zip_code           &lt;chr&gt; &quot;98108&quot;, &quot;98117&quot;, &quot;98136&quot;, &quot;98117&quot;, &quot;98144&quot;...</code></pre>
<p>We will now create two separate data frames, one for cats and one for dogs.</p>
<pre class="r"><code># cats dataframe
cats_names &lt;- pet_names %&gt;%
  filter(species == &quot;Cat&quot;)


# dogs dataframe
dogs_names &lt;- pet_names %&gt;% 
  filter(species == &quot;Dog&quot;)</code></pre>
<p>Let’s start to manipulate strings! Now, we’ll use two different functions from the stringr package: <code>str_remove_all</code> to remove all punctuations in the names and <code>str_squish</code> to remove all excess white space.</p>
<pre class="r"><code># cats new dataframe
cats_names_tbl &lt;- cats_names %&gt;% 
  mutate(
    animals_name = 
      animals_name %&gt;%
      str_remove_all(pattern = &quot;[:punct:]&quot;) %&gt;% # remove punctuation
      str_squish()) # remove all excess white space

# explore the data
cats_names_tbl %&gt;%
  head(15) %&gt;% 
  kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
license_issue_date
</th>
<th style="text-align:left;">
license_number
</th>
<th style="text-align:left;">
animals_name
</th>
<th style="text-align:left;">
species
</th>
<th style="text-align:left;">
primary_breed
</th>
<th style="text-align:left;">
secondary_breed
</th>
<th style="text-align:left;">
zip_code
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
November 23 2018
</td>
<td style="text-align:left;">
824666
</td>
<td style="text-align:left;">
Melb
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98117
</td>
</tr>
<tr>
<td style="text-align:left;">
December 30 2018
</td>
<td style="text-align:left;">
S119138
</td>
<td style="text-align:left;">
Gingersnap
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98144
</td>
</tr>
<tr>
<td style="text-align:left;">
August 09 2018
</td>
<td style="text-align:left;">
S142558
</td>
<td style="text-align:left;">
Sebastian
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98122
</td>
</tr>
<tr>
<td style="text-align:left;">
August 20 2018
</td>
<td style="text-align:left;">
S142546
</td>
<td style="text-align:left;">
Madeline
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98105
</td>
</tr>
<tr>
<td style="text-align:left;">
December 08 2018
</td>
<td style="text-align:left;">
S123830
</td>
<td style="text-align:left;">
Cleo
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98199
</td>
</tr>
<tr>
<td style="text-align:left;">
October 20 2018
</td>
<td style="text-align:left;">
S149153
</td>
<td style="text-align:left;">
Glitch
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Siamese
</td>
<td style="text-align:left;">
Domestic Medium Hair
</td>
<td style="text-align:left;">
98122
</td>
</tr>
<tr>
<td style="text-align:left;">
November 24 2018
</td>
<td style="text-align:left;">
817137
</td>
<td style="text-align:left;">
Candy
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98126
</td>
</tr>
<tr>
<td style="text-align:left;">
December 07 2018
</td>
<td style="text-align:left;">
895346
</td>
<td style="text-align:left;">
Cinnamon
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98144
</td>
</tr>
<tr>
<td style="text-align:left;">
October 31 2018
</td>
<td style="text-align:left;">
S123360
</td>
<td style="text-align:left;">
Sydney2
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Medium Hair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98101
</td>
</tr>
<tr>
<td style="text-align:left;">
October 23 2018
</td>
<td style="text-align:left;">
S122244
</td>
<td style="text-align:left;">
Calvin
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
American Shorthair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98119
</td>
</tr>
<tr>
<td style="text-align:left;">
November 15 2018
</td>
<td style="text-align:left;">
8002730
</td>
<td style="text-align:left;">
Mochi
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Medium Hair
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98105
</td>
</tr>
<tr>
<td style="text-align:left;">
November 27 2018
</td>
<td style="text-align:left;">
S125276
</td>
<td style="text-align:left;">
dmh
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Medium Hair
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98117
</td>
</tr>
<tr>
<td style="text-align:left;">
December 20 2018
</td>
<td style="text-align:left;">
952291
</td>
<td style="text-align:left;">
Justin
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Medium Hair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98122
</td>
</tr>
<tr>
<td style="text-align:left;">
December 21 2018
</td>
<td style="text-align:left;">
S150217
</td>
<td style="text-align:left;">
Dash
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98117
</td>
</tr>
<tr>
<td style="text-align:left;">
December 10 2018
</td>
<td style="text-align:left;">
8003722
</td>
<td style="text-align:left;">
Buster
</td>
<td style="text-align:left;">
Cat
</td>
<td style="text-align:left;">
Domestic Shorthair
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98115
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># dogs new dataframe
dogs_names_tbl &lt;- dogs_names %&gt;% 
  mutate(
    animals_name = 
      animals_name %&gt;%
      str_remove_all(pattern = &quot;[:punct:]&quot;) %&gt;% # remove punctuation
      str_squish()) # remove all excess white space

dogs_names_tbl %&gt;%
  head(15) %&gt;% 
  kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
license_issue_date
</th>
<th style="text-align:left;">
license_number
</th>
<th style="text-align:left;">
animals_name
</th>
<th style="text-align:left;">
species
</th>
<th style="text-align:left;">
primary_breed
</th>
<th style="text-align:left;">
secondary_breed
</th>
<th style="text-align:left;">
zip_code
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
November 16 2018
</td>
<td style="text-align:left;">
8002756
</td>
<td style="text-align:left;">
WallE
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Mixed Breed, Medium (up to 44 lbs fully grown)
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98108
</td>
</tr>
<tr>
<td style="text-align:left;">
November 11 2018
</td>
<td style="text-align:left;">
S124529
</td>
<td style="text-align:left;">
Andre
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Terrier, Jack Russell
</td>
<td style="text-align:left;">
Dachshund, Standard Wire Haired
</td>
<td style="text-align:left;">
98117
</td>
</tr>
<tr>
<td style="text-align:left;">
November 21 2018
</td>
<td style="text-align:left;">
903793
</td>
<td style="text-align:left;">
Mac
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Retriever, Labrador
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98136
</td>
</tr>
<tr>
<td style="text-align:left;">
December 16 2018
</td>
<td style="text-align:left;">
S138529
</td>
<td style="text-align:left;">
Cody
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Retriever, Labrador
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98103
</td>
</tr>
<tr>
<td style="text-align:left;">
October 04 2017
</td>
<td style="text-align:left;">
580652
</td>
<td style="text-align:left;">
Millie
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Terrier, Boston
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98115
</td>
</tr>
<tr>
<td style="text-align:left;">
December 23 2018
</td>
<td style="text-align:left;">
961052
</td>
<td style="text-align:left;">
Sabre
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Terrier
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98126
</td>
</tr>
<tr>
<td style="text-align:left;">
December 07 2018
</td>
<td style="text-align:left;">
S125461
</td>
<td style="text-align:left;">
Thomas
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Chihuahua, Short Coat
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98177
</td>
</tr>
<tr>
<td style="text-align:left;">
November 07 2018
</td>
<td style="text-align:left;">
8002543
</td>
<td style="text-align:left;">
Lulu
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Vizsla, Smooth Haired
</td>
<td style="text-align:left;">
Mix
</td>
<td style="text-align:left;">
98105
</td>
</tr>
<tr>
<td style="text-align:left;">
December 15 2018
</td>
<td style="text-align:left;">
S138838
</td>
<td style="text-align:left;">
Milo
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Boxer
</td>
<td style="text-align:left;">
Retriever, Labrador
</td>
<td style="text-align:left;">
98109
</td>
</tr>
<tr>
<td style="text-align:left;">
November 27 2018
</td>
<td style="text-align:left;">
S123980
</td>
<td style="text-align:left;">
Anubis
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Poodle, Standard
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98112
</td>
</tr>
<tr>
<td style="text-align:left;">
October 25 2018
</td>
<td style="text-align:left;">
830506
</td>
<td style="text-align:left;">
Skylar
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Border Collie
</td>
<td style="text-align:left;">
Terrier, Airedale
</td>
<td style="text-align:left;">
98144
</td>
</tr>
<tr>
<td style="text-align:left;">
October 23 2018
</td>
<td style="text-align:left;">
S137719
</td>
<td style="text-align:left;">
Cleo
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Bernese Mountain Dog
</td>
<td style="text-align:left;">
Spaniel
</td>
<td style="text-align:left;">
98107
</td>
</tr>
<tr>
<td style="text-align:left;">
November 07 2018
</td>
<td style="text-align:left;">
905090
</td>
<td style="text-align:left;">
Petey
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Pomeranian
</td>
<td style="text-align:left;">
Shih Tzu
</td>
<td style="text-align:left;">
98119
</td>
</tr>
<tr>
<td style="text-align:left;">
December 24 2018
</td>
<td style="text-align:left;">
S152290
</td>
<td style="text-align:left;">
Kaia
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Karelian Bear Dog
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98117
</td>
</tr>
<tr>
<td style="text-align:left;">
December 27 2018
</td>
<td style="text-align:left;">
8004142
</td>
<td style="text-align:left;">
Maya
</td>
<td style="text-align:left;">
Dog
</td>
<td style="text-align:left;">
Chihuahua, Short Coat
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
98126
</td>
</tr>
</tbody>
</table>
<p>One of our goals is to know the number of words that every name set has. In this case, we should use the <code>str_count</code> function with the regex pattern <code>\\w+</code> so that the white space is not included as a word.</p>
<pre class="r"><code># count the number of words 
# for cats
cats_names_tbl %&gt;% 
  mutate(count_words = str_count(animals_name, pattern = &quot;\\w+&quot;)) %&gt;%
  arrange(desc(count_words)) %&gt;%
  select(animals_name, count_words) %&gt;%
  head()</code></pre>
<pre><code>##                                    animals_name count_words
## 1         King Charles Leon the First aka Chuck           7
## 2           Lady G Lolo Paloma MacGuffie Hunter           6
## 3 Her Ladyship Princess Penelope Peachfuzz Howe           6
## 4               Morris Boney T MacGuffie Hunter           5
## 5                Fern River Brits Gouda Reserve           5
## 6            Jazzmine Primula Rosamund the Fair           5</code></pre>
<pre class="r"><code># for dogs
dogs_names_tbl %&gt;% 
  mutate(count_words = str_count(animals_name, pattern = &quot;\\w+&quot;)) %&gt;%
  arrange(desc(count_words)) %&gt;%
  select(animals_name, count_words) %&gt;%
  head()</code></pre>
<pre><code>##                                              animals_name count_words
## 1            Little Miss Dublin Maeve of the Emerald Isle           8
## 2              Legends of Olde Sir Walter The Lady Killer           8
## 3                   Cascade Mountains Out of a Dream BRIA           7
## 4 NuitÂ AhathoorÂ HecateÂ SapphoÂ JezebelÂ Lilith Crowley           7
## 5                   His Royal Highness the Duke of Tacoma           7
## 6           Lady Kassandra Yu Countess of Wallingford KBE           7</code></pre>
<p>So, the cat’s name with more words has 7 name sets, namely “King Charles Leon the First aka Chuck”. The dogs’ names with more words have 8 name sets and they’re called “Little Miss Dublin Maeve of the Emerald Isle” and “Legends of Olde Sir Walter The Lady Killer”.</p>
<p>Let’s imagine we wanted to know the number of characters of each pet instead of knowing the number of name sets of each dog and cat. In this scenario, we could use the <code>str_length</code> function. First, we will use the <code>str_remove_all</code> to remove the white spaces followed by the <code>str_length</code> function.</p>
<pre class="r"><code># find the number of characters
# for cats
cats_names_tbl %&gt;% 
  mutate(animals_name_rem = animals_name %&gt;% str_remove_all(pattern = &quot; &quot;),
         number_char = animals_name_rem %&gt;% str_length()) %&gt;%
  select(animals_name, number_char) %&gt;% 
  arrange(desc(number_char)) %&gt;%
  head()</code></pre>
<pre><code>##                                    animals_name number_char
## 1 Her Ladyship Princess Penelope Peachfuzz Howe          40
## 2         King Charles Leon the First aka Chuck          31
## 3           Lady G Lolo Paloma MacGuffie Hunter          30
## 4            Jazzmine Primula Rosamund the Fair          30
## 5              Ginger Chanel OBrien SpletzKauff          29
## 6               Samantha Scully HammerstromGuel          29</code></pre>
<pre class="r"><code># for dogs
dogs_names_tbl %&gt;% 
  mutate(animals_name_rem = animals_name %&gt;% str_remove_all(pattern = &quot; &quot;),
         number_char = animals_name_rem %&gt;% str_length()) %&gt;%
 select(animals_name, number_char) %&gt;% 
arrange(desc(number_char)) %&gt;%
  head()</code></pre>
<pre><code>##                                              animals_name number_char
## 1 NuitÂ AhathoorÂ HecateÂ SapphoÂ JezebelÂ Lilith Crowley          49
## 2             Greta McGonagall Galactica Sunnydale Fugent          39
## 3           Lady Kassandra Yu Countess of Wallingford KBE          39
## 4            Little Miss Dublin Maeve of the Emerald Isle          37
## 5              Legends of Olde Sir Walter The Lady Killer          35
## 6                   Lotus Birdie Snufflepupagus Underfoot          34</code></pre>
<p>40 characters is the maximum number of characters for cats, while for dogs the maximum number is 49.</p>
<p>We can also manipulate if a string is in upper case or lower case. For this, we can use the <code>str_to_upper</code> and <code>str_to_lower</code> functions, respectively.</p>
<p>Note: From now on well use the pets’ names with lower cases.</p>
<pre class="r"><code># to upper case
# for cats
cats_names_tbl %&gt;% 
  mutate(animals_name = animals_name %&gt;% str_to_upper()) %&gt;%
  head()</code></pre>
<pre><code>##   license_issue_date license_number animals_name species
## 1   November 23 2018         824666         MELB     Cat
## 2   December 30 2018        S119138   GINGERSNAP     Cat
## 3     August 09 2018        S142558    SEBASTIAN     Cat
## 4     August 20 2018        S142546     MADELINE     Cat
## 5   December 08 2018        S123830         CLEO     Cat
## 6    October 20 2018        S149153       GLITCH     Cat
##        primary_breed      secondary_breed zip_code
## 1 Domestic Shorthair                 &lt;NA&gt;    98117
## 2 Domestic Shorthair                  Mix    98144
## 3 Domestic Shorthair                  Mix    98122
## 4 Domestic Shorthair                  Mix    98105
## 5 Domestic Shorthair                 &lt;NA&gt;    98199
## 6            Siamese Domestic Medium Hair    98122</code></pre>
<pre class="r"><code># for dogs
dogs_names_tbl %&gt;% 
  mutate(animals_name = animals_name %&gt;% str_to_upper()) %&gt;%
  head()</code></pre>
<pre><code>##   license_issue_date license_number animals_name species
## 1   November 16 2018        8002756        WALLE     Dog
## 2   November 11 2018        S124529        ANDRE     Dog
## 3   November 21 2018         903793          MAC     Dog
## 4   December 16 2018        S138529         CODY     Dog
## 5    October 04 2017         580652       MILLIE     Dog
## 6   December 23 2018         961052        SABRE     Dog
##                                    primary_breed
## 1 Mixed Breed, Medium (up to 44 lbs fully grown)
## 2                          Terrier, Jack Russell
## 3                            Retriever, Labrador
## 4                            Retriever, Labrador
## 5                                Terrier, Boston
## 6                                        Terrier
##                   secondary_breed zip_code
## 1                             Mix    98108
## 2 Dachshund, Standard Wire Haired    98117
## 3                            &lt;NA&gt;    98136
## 4                            &lt;NA&gt;    98103
## 5                            &lt;NA&gt;    98115
## 6                            &lt;NA&gt;    98126</code></pre>
<pre class="r"><code># to lower case
# for cats
cats_names_tbl &lt;- cats_names_tbl %&gt;% 
  mutate(animals_name = animals_name %&gt;% str_to_lower()) 

# for dogs
dogs_names_tbl &lt;- dogs_names_tbl %&gt;% 
  mutate(animals_name = animals_name %&gt;% str_to_lower()) </code></pre>
<p>Before any further analysis, we will separate the pets’ names in different columns. With stringr we can use the <code>str_c</code> or the <code>str_split</code> function, but to be honest I prefer using the <code>cSplit</code> function from the <code>splitstackshape</code>.</p>
<pre class="r"><code># separate columns with str_c
# for cats
cats_names_tbl %&gt;% 
  separate(animals_name,
           into = str_c(&quot;animals_name&quot;, 1:7), # 7 because that&#39;s the maximum number of words
           sep = &quot; &quot;,
           remove = FALSE,
           extra = &quot;drop&quot;) %&gt;%
  head()</code></pre>
<pre><code>## Warning: Expected 7 pieces. Missing pieces filled with `NA` in 16887
## rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
## 20, ...].</code></pre>
<pre><code>##   license_issue_date license_number animals_name animals_name1
## 1   November 23 2018         824666         melb          melb
## 2   December 30 2018        S119138   gingersnap    gingersnap
## 3     August 09 2018        S142558    sebastian     sebastian
## 4     August 20 2018        S142546     madeline      madeline
## 5   December 08 2018        S123830         cleo          cleo
## 6    October 20 2018        S149153       glitch        glitch
##   animals_name2 animals_name3 animals_name4 animals_name5 animals_name6
## 1          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 2          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 3          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 4          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 5          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 6          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
##   animals_name7 species      primary_breed      secondary_breed zip_code
## 1          &lt;NA&gt;     Cat Domestic Shorthair                 &lt;NA&gt;    98117
## 2          &lt;NA&gt;     Cat Domestic Shorthair                  Mix    98144
## 3          &lt;NA&gt;     Cat Domestic Shorthair                  Mix    98122
## 4          &lt;NA&gt;     Cat Domestic Shorthair                  Mix    98105
## 5          &lt;NA&gt;     Cat Domestic Shorthair                 &lt;NA&gt;    98199
## 6          &lt;NA&gt;     Cat            Siamese Domestic Medium Hair    98122</code></pre>
<pre class="r"><code># separate columns with str_c
# for dogs
dogs_names_tbl %&gt;% 
  separate(animals_name,
           into = str_c(&quot;animals_name&quot;, 1:8), # 8 because that&#39;s the maximum number of words
           sep = &quot; &quot;,
           remove = FALSE,
           extra = &quot;drop&quot;) %&gt;%
  head()</code></pre>
<pre><code>## Warning: Expected 8 pieces. Missing pieces filled with `NA` in 35103
## rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
## 20, ...].</code></pre>
<pre><code>##   license_issue_date license_number animals_name animals_name1
## 1   November 16 2018        8002756        walle         walle
## 2   November 11 2018        S124529        andre         andre
## 3   November 21 2018         903793          mac           mac
## 4   December 16 2018        S138529         cody          cody
## 5    October 04 2017         580652       millie        millie
## 6   December 23 2018         961052        sabre         sabre
##   animals_name2 animals_name3 animals_name4 animals_name5 animals_name6
## 1          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 2          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 3          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 4          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 5          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 6          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
##   animals_name7 animals_name8 species
## 1          &lt;NA&gt;          &lt;NA&gt;     Dog
## 2          &lt;NA&gt;          &lt;NA&gt;     Dog
## 3          &lt;NA&gt;          &lt;NA&gt;     Dog
## 4          &lt;NA&gt;          &lt;NA&gt;     Dog
## 5          &lt;NA&gt;          &lt;NA&gt;     Dog
## 6          &lt;NA&gt;          &lt;NA&gt;     Dog
##                                    primary_breed
## 1 Mixed Breed, Medium (up to 44 lbs fully grown)
## 2                          Terrier, Jack Russell
## 3                            Retriever, Labrador
## 4                            Retriever, Labrador
## 5                                Terrier, Boston
## 6                                        Terrier
##                   secondary_breed zip_code
## 1                             Mix    98108
## 2 Dachshund, Standard Wire Haired    98117
## 3                            &lt;NA&gt;    98136
## 4                            &lt;NA&gt;    98103
## 5                            &lt;NA&gt;    98115
## 6                            &lt;NA&gt;    98126</code></pre>
<pre class="r"><code># separate columns with str_split
# for cats
splitting1 &lt;- as.data.frame(str_split(cats_names_tbl$animals_name, fixed(&quot; &quot;), n = 7, simplify = TRUE)) # 7 because that&#39;s the maximum number of words

cats_after_split &lt;- bind_cols(cats_names_tbl, splitting1)

# separate columns with str_split
# for dogs
splitting2 &lt;- as.data.frame(str_split(dogs_names_tbl$animals_name, fixed(&quot; &quot;), n = 8, simplify = TRUE)) # 8 because that&#39;s the maximum number of words

cats_after_split &lt;- bind_cols(dogs_names_tbl, splitting2)</code></pre>
<p>With the <code>cSplit</code> function gets simpler.</p>
<pre class="r"><code># with the cSplit function
# for cats
cats_names_tbl &lt;- cats_names_tbl %&gt;%
  cSplit(&quot;animals_name&quot;, sep = &quot; &quot;, drop = FALSE) # separate animals_name column, but keep it

cats_names_tbl %&gt;%
  head(20) </code></pre>
<pre><code>##     license_issue_date license_number animals_name species
##  1:   November 23 2018         824666         melb     Cat
##  2:   December 30 2018        S119138   gingersnap     Cat
##  3:     August 09 2018        S142558    sebastian     Cat
##  4:     August 20 2018        S142546     madeline     Cat
##  5:   December 08 2018        S123830         cleo     Cat
##  6:    October 20 2018        S149153       glitch     Cat
##  7:   November 24 2018         817137        candy     Cat
##  8:   December 07 2018         895346     cinnamon     Cat
##  9:    October 31 2018        S123360      sydney2     Cat
## 10:    October 23 2018        S122244       calvin     Cat
## 11:   November 15 2018        8002730        mochi     Cat
## 12:   November 27 2018        S125276          dmh     Cat
## 13:   December 20 2018         952291       justin     Cat
## 14:   December 21 2018        S150217         dash     Cat
## 15:   December 10 2018        8003722       buster     Cat
## 16:    October 21 2018        S136705         monk     Cat
## 17:    October 29 2018        S137285         mari     Cat
## 18:   November 19 2018        S124303         peko     Cat
## 19:   November 07 2018         896862        sajah     Cat
## 20:   November 12 2018         896813         nami     Cat
##            primary_breed      secondary_breed zip_code animals_name_1
##  1:   Domestic Shorthair                 &lt;NA&gt;    98117           melb
##  2:   Domestic Shorthair                  Mix    98144     gingersnap
##  3:   Domestic Shorthair                  Mix    98122      sebastian
##  4:   Domestic Shorthair                  Mix    98105       madeline
##  5:   Domestic Shorthair                 &lt;NA&gt;    98199           cleo
##  6:              Siamese Domestic Medium Hair    98122         glitch
##  7:   Domestic Shorthair                 &lt;NA&gt;    98126          candy
##  8:   Domestic Shorthair                 &lt;NA&gt;    98144       cinnamon
##  9: Domestic Medium Hair                 &lt;NA&gt;    98101        sydney2
## 10:   American Shorthair                 &lt;NA&gt;    98119         calvin
## 11: Domestic Medium Hair                  Mix    98105          mochi
## 12: Domestic Medium Hair                  Mix    98117            dmh
## 13: Domestic Medium Hair                 &lt;NA&gt;    98122         justin
## 14:   Domestic Shorthair                 &lt;NA&gt;    98117           dash
## 15:   Domestic Shorthair                  Mix    98115         buster
## 16: Domestic Medium Hair                  Mix    98122           monk
## 17:   Domestic Shorthair                 &lt;NA&gt;    98144           mari
## 18: Domestic Medium Hair                 &lt;NA&gt;    98117           peko
## 19: Domestic Medium Hair                 &lt;NA&gt;    98112          sajah
## 20:   Domestic Shorthair                 &lt;NA&gt;    98107           nami
##     animals_name_2 animals_name_3 animals_name_4 animals_name_5
##  1:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  2:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  3:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  4:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  5:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  6:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  7:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  8:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  9:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 10:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 11:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 12:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 13:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 14:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 15:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 16:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 17:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 18:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 19:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 20:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##     animals_name_6 animals_name_7
##  1:           &lt;NA&gt;           &lt;NA&gt;
##  2:           &lt;NA&gt;           &lt;NA&gt;
##  3:           &lt;NA&gt;           &lt;NA&gt;
##  4:           &lt;NA&gt;           &lt;NA&gt;
##  5:           &lt;NA&gt;           &lt;NA&gt;
##  6:           &lt;NA&gt;           &lt;NA&gt;
##  7:           &lt;NA&gt;           &lt;NA&gt;
##  8:           &lt;NA&gt;           &lt;NA&gt;
##  9:           &lt;NA&gt;           &lt;NA&gt;
## 10:           &lt;NA&gt;           &lt;NA&gt;
## 11:           &lt;NA&gt;           &lt;NA&gt;
## 12:           &lt;NA&gt;           &lt;NA&gt;
## 13:           &lt;NA&gt;           &lt;NA&gt;
## 14:           &lt;NA&gt;           &lt;NA&gt;
## 15:           &lt;NA&gt;           &lt;NA&gt;
## 16:           &lt;NA&gt;           &lt;NA&gt;
## 17:           &lt;NA&gt;           &lt;NA&gt;
## 18:           &lt;NA&gt;           &lt;NA&gt;
## 19:           &lt;NA&gt;           &lt;NA&gt;
## 20:           &lt;NA&gt;           &lt;NA&gt;</code></pre>
<pre class="r"><code># with the cSplit function
# for dogs
dogs_names_tbl &lt;- dogs_names_tbl %&gt;%
  cSplit(&quot;animals_name&quot;, sep = &quot; &quot;, drop = FALSE) # separate animals_name column, but keep it


dogs_names_tbl %&gt;%
  head(20)</code></pre>
<pre><code>##     license_issue_date license_number animals_name species
##  1:   November 16 2018        8002756        walle     Dog
##  2:   November 11 2018        S124529        andre     Dog
##  3:   November 21 2018         903793          mac     Dog
##  4:   December 16 2018        S138529         cody     Dog
##  5:    October 04 2017         580652       millie     Dog
##  6:   December 23 2018         961052        sabre     Dog
##  7:   December 07 2018        S125461       thomas     Dog
##  8:   November 07 2018        8002543         lulu     Dog
##  9:   December 15 2018        S138838         milo     Dog
## 10:   November 27 2018        S123980       anubis     Dog
## 11:    October 25 2018         830506       skylar     Dog
## 12:    October 23 2018        S137719         cleo     Dog
## 13:   November 07 2018         905090        petey     Dog
## 14:   December 24 2018        S152290         kaia     Dog
## 15:   December 27 2018        8004142         maya     Dog
## 16:   November 18 2018         835221      shirley     Dog
## 17:    October 18 2018        S101544       diesel     Dog
## 18:   November 30 2018         904438        jacob     Dog
## 19:   November 06 2018        8002506       linkin     Dog
## 20:   December 02 2018         829922       gracie     Dog
##                                      primary_breed
##  1: Mixed Breed, Medium (up to 44 lbs fully grown)
##  2:                          Terrier, Jack Russell
##  3:                            Retriever, Labrador
##  4:                            Retriever, Labrador
##  5:                                Terrier, Boston
##  6:                                        Terrier
##  7:                          Chihuahua, Short Coat
##  8:                          Vizsla, Smooth Haired
##  9:                                          Boxer
## 10:                               Poodle, Standard
## 11:                                  Border Collie
## 12:                           Bernese Mountain Dog
## 13:                                     Pomeranian
## 14:                              Karelian Bear Dog
## 15:                          Chihuahua, Short Coat
## 16:                            Australian Shepherd
## 17:                                       Shepherd
## 18:                                German Shepherd
## 19:                          Vizsla, Smooth Haired
## 20:                           Terrier, Fox, Smooth
##                     secondary_breed zip_code animals_name_1 animals_name_2
##  1:                             Mix    98108          walle           &lt;NA&gt;
##  2: Dachshund, Standard Wire Haired    98117          andre           &lt;NA&gt;
##  3:                            &lt;NA&gt;    98136            mac           &lt;NA&gt;
##  4:                            &lt;NA&gt;    98103           cody           &lt;NA&gt;
##  5:                            &lt;NA&gt;    98115         millie           &lt;NA&gt;
##  6:                            &lt;NA&gt;    98126          sabre           &lt;NA&gt;
##  7:                             Mix    98177         thomas           &lt;NA&gt;
##  8:                             Mix    98105           lulu           &lt;NA&gt;
##  9:             Retriever, Labrador    98109           milo           &lt;NA&gt;
## 10:                            &lt;NA&gt;    98112         anubis           &lt;NA&gt;
## 11:               Terrier, Airedale    98144         skylar           &lt;NA&gt;
## 12:                         Spaniel    98107           cleo           &lt;NA&gt;
## 13:                        Shih Tzu    98119          petey           &lt;NA&gt;
## 14:                            &lt;NA&gt;    98117           kaia           &lt;NA&gt;
## 15:                            &lt;NA&gt;    98126           maya           &lt;NA&gt;
## 16:               Retriever, Golden    98144        shirley           &lt;NA&gt;
## 17:                             Mix    98118         diesel           &lt;NA&gt;
## 18:                      Rottweiler    98199          jacob           &lt;NA&gt;
## 19:                            &lt;NA&gt;    98105         linkin           &lt;NA&gt;
## 20:                            &lt;NA&gt;    98118         gracie           &lt;NA&gt;
##     animals_name_3 animals_name_4 animals_name_5 animals_name_6
##  1:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  2:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  3:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  4:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  5:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  6:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  7:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  8:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##  9:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 10:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 11:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 12:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 13:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 14:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 15:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 16:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 17:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 18:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 19:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
## 20:           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;           &lt;NA&gt;
##     animals_name_7 animals_name_8
##  1:           &lt;NA&gt;           &lt;NA&gt;
##  2:           &lt;NA&gt;           &lt;NA&gt;
##  3:           &lt;NA&gt;           &lt;NA&gt;
##  4:           &lt;NA&gt;           &lt;NA&gt;
##  5:           &lt;NA&gt;           &lt;NA&gt;
##  6:           &lt;NA&gt;           &lt;NA&gt;
##  7:           &lt;NA&gt;           &lt;NA&gt;
##  8:           &lt;NA&gt;           &lt;NA&gt;
##  9:           &lt;NA&gt;           &lt;NA&gt;
## 10:           &lt;NA&gt;           &lt;NA&gt;
## 11:           &lt;NA&gt;           &lt;NA&gt;
## 12:           &lt;NA&gt;           &lt;NA&gt;
## 13:           &lt;NA&gt;           &lt;NA&gt;
## 14:           &lt;NA&gt;           &lt;NA&gt;
## 15:           &lt;NA&gt;           &lt;NA&gt;
## 16:           &lt;NA&gt;           &lt;NA&gt;
## 17:           &lt;NA&gt;           &lt;NA&gt;
## 18:           &lt;NA&gt;           &lt;NA&gt;
## 19:           &lt;NA&gt;           &lt;NA&gt;
## 20:           &lt;NA&gt;           &lt;NA&gt;</code></pre>
<p>Let us now find the most common first and last letters used in the first name for both cats and dogs. For this, we will use the <code>str_sub</code> function.</p>
<pre class="r"><code># first letter
# for cats
cats_names_tbl %&gt;% 
  mutate(first_letter = animals_name_1 %&gt;% str_sub(1,1)) %&gt;%
  count(first_letter) %&gt;%
  arrange(desc(n)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 2
##   first_letter     n
##   &lt;chr&gt;        &lt;int&gt;
## 1 m             1998
## 2 s             1831
## 3 b             1356
## 4 c             1234
## 5 l             1142
## 6 p             1095</code></pre>
<pre class="r"><code># for dogs
dogs_names_tbl %&gt;% 
  mutate(first_letter = animals_name_1 %&gt;% str_sub(1,1)) %&gt;%
  count(first_letter) %&gt;%
  arrange(desc(n)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 2
##   first_letter     n
##   &lt;chr&gt;        &lt;int&gt;
## 1 m             3408
## 2 b             3366
## 3 s             3042
## 4 c             2760
## 5 l             2712
## 6 r             2199</code></pre>
<pre class="r"><code># last letter
# for cats
cats_names_tbl %&gt;% 
  mutate(last_letter = animals_name_1 %&gt;% str_sub(-1,-1)) %&gt;%
  count(last_letter) %&gt;%
  arrange(desc(n)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 2
##   last_letter     n
##   &lt;chr&gt;       &lt;int&gt;
## 1 y            2881
## 2 e            2855
## 3 a            2406
## 4 r            1368
## 5 o            1209
## 6 s            1110</code></pre>
<pre class="r"><code># for dogs
dogs_names_tbl %&gt;% 
  mutate(last_letter = animals_name_1 %&gt;% str_sub(-1,-1)) %&gt;%
  count(last_letter) %&gt;%
  arrange(desc(n)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 2
##   last_letter     n
##   &lt;chr&gt;       &lt;int&gt;
## 1 y            7373
## 2 e            6575
## 3 a            4839
## 4 r            3007
## 5 o            2684
## 6 n            2159</code></pre>
<p>The letter “M” seems to be the preferred one when naming both cats and dogs. Curiously, the letter “Y” is picked more often by the pet owners for the name ending.</p>
<p>After this, our goal is to find the most common names for cats and dogs.</p>
<pre class="r"><code># most common name
# for cats
cats_names_tbl %&gt;%
  filter(!is.na(animals_name_1)) %&gt;% 
  count(animals_name_1) %&gt;%
  arrange(desc(n)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 2
##   animals_name_1     n
##   &lt;fct&gt;          &lt;int&gt;
## 1 luna             116
## 2 lucy             104
## 3 lily              91
## 4 charlie           88
## 5 max               86
## 6 bella             84</code></pre>
<pre class="r"><code># for dogs
dogs_names_tbl %&gt;% 
  filter(!is.na(animals_name_1)) %&gt;% 
  count(animals_name_1) %&gt;%
  arrange(desc(n)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 2
##   animals_name_1     n
##   &lt;fct&gt;          &lt;int&gt;
## 1 lucy             358
## 2 charlie          325
## 3 bella            273
## 4 luna             261
## 5 daisy            244
## 6 cooper           199</code></pre>
<p>“Luna” is the most popular name for cats, while for dogs “Lucy” is the name given more often.</p>
<p>Back again to <code>stringr</code>, it would be possible to use <code>str_subset</code> to find names with a specific pattern.</p>
<pre class="r"><code># find unique first names with the pattern &quot;su&quot;
# for cats
unique(str_subset(cats_names_tbl$animals_name_1, pattern = &quot;su&quot;))</code></pre>
<pre><code>##  [1] &quot;sugar&quot;      &quot;summer&quot;     &quot;sunny&quot;      &quot;suzie&quot;      &quot;sufjan&quot;    
##  [6] &quot;susie&quot;      &quot;sushi&quot;      &quot;sunbeam&quot;    &quot;sunset&quot;     &quot;suki&quot;      
## [11] &quot;susu&quot;       &quot;natsumi&quot;    &quot;ursula&quot;     &quot;suri&quot;       &quot;graysun&quot;   
## [16] &quot;sultana&quot;    &quot;suess&quot;      &quot;tsunami&quot;    &quot;sisu&quot;       &quot;sumi&quot;      
## [21] &quot;sundae&quot;     &quot;sukapati&quot;   &quot;sullivan&quot;   &quot;suika&quot;      &quot;sultrina&quot;  
## [26] &quot;katsu&quot;      &quot;sula&quot;       &quot;sumo&quot;       &quot;suede&quot;      &quot;suma&quot;      
## [31] &quot;sundance&quot;   &quot;sunshine&quot;   &quot;sugarpuffs&quot; &quot;sukhi&quot;      &quot;sunkist&quot;   
## [36] &quot;sunflower&quot;  &quot;sunnyside&quot;  &quot;sutton&quot;     &quot;sucha&quot;      &quot;yasuo&quot;     
## [41] &quot;sully&quot;      &quot;mitsu&quot;      &quot;suji&quot;       &quot;sunday&quot;     &quot;sukie&quot;     
## [46] &quot;satsuma&quot;    &quot;zasu&quot;       &quot;misu&quot;       &quot;suzykitty&quot;  &quot;surya&quot;     
## [51] &quot;natsu&quot;      &quot;nasuchan&quot;   &quot;suzy&quot;       &quot;tonkatsu&quot;   &quot;suzi&quot;      
## [56] &quot;susan&quot;      &quot;superman&quot;   &quot;suva&quot;       &quot;suleyman&quot;   &quot;tsuki&quot;     
## [61] &quot;sulley&quot;</code></pre>
<pre class="r"><code># for dogs
unique(str_subset(dogs_names_tbl$animals_name_1, pattern = &quot;su&quot;))</code></pre>
<pre><code>##  [1] &quot;sue&quot;          &quot;suzie&quot;        &quot;suki&quot;         &quot;sully&quot;       
##  [5] &quot;susie&quot;        &quot;sunny&quot;        &quot;suzy&quot;         &quot;ursula&quot;      
##  [9] &quot;sushi&quot;        &quot;sugar&quot;        &quot;sun&quot;          &quot;katsu&quot;       
## [13] &quot;mitsu&quot;        &quot;jesus&quot;        &quot;sunshine&quot;     &quot;su&quot;          
## [17] &quot;summer&quot;       &quot;sukey&quot;        &quot;tamotsu&quot;      &quot;sundae&quot;      
## [21] &quot;kitsunejip&quot;   &quot;sunchaser&quot;    &quot;missus&quot;       &quot;suri&quot;        
## [25] &quot;sumi&quot;         &quot;komatsu&quot;      &quot;suggen&quot;       &quot;yousuke&quot;     
## [29] &quot;sundance&quot;     &quot;sudo&quot;         &quot;tsuki&quot;        &quot;sunnee&quot;      
## [33] &quot;sukhi&quot;        &quot;sunday&quot;       &quot;tsunami&quot;      &quot;jessup&quot;      
## [37] &quot;subaru&quot;       &quot;rayasunshine&quot; &quot;susannah&quot;     &quot;tsukee&quot;      
## [41] &quot;bosun&quot;        &quot;sullivan&quot;     &quot;suka&quot;         &quot;subotai&quot;     
## [45] &quot;sunniva&quot;      &quot;suzzie&quot;       &quot;sug&quot;          &quot;zsuska&quot;      
## [49] &quot;asuka&quot;        &quot;sisu&quot;         &quot;sukie&quot;        &quot;sunup&quot;       
## [53] &quot;sucia&quot;        &quot;suni&quot;         &quot;sutter&quot;       &quot;suzieq&quot;      
## [57] &quot;subi&quot;         &quot;surti&quot;        &quot;sumo&quot;         &quot;suze&quot;        
## [61] &quot;sugarberry&quot;   &quot;jitsu&quot;        &quot;summit&quot;       &quot;sukha&quot;       
## [65] &quot;sudi&quot;         &quot;sultan&quot;       &quot;kitsune&quot;      &quot;susi&quot;        
## [69] &quot;colossus&quot;     &quot;sukoshi&quot;      &quot;narcissus&quot;    &quot;sua&quot;         
## [73] &quot;kietsu&quot;       &quot;sugi&quot;         &quot;suma&quot;         &quot;sukee&quot;       
## [77] &quot;misu&quot;         &quot;suzee&quot;        &quot;consuela&quot;</code></pre>
<p>Therefore, we have 61 unique cat names with the pattern “su”. For dogs this pattern appears more often, meaning 79 unique occurrences.</p>
<p><code>str_which</code> is another interesting function which tell us in which row a specific pattern occurs.</p>
<pre class="r"><code># find a pattern row location
# for cats
str_which(cats_names_tbl$animals_name_1, pattern = &quot;car&quot;)</code></pre>
<pre><code>##   [1]    53   180   271   397   449   811   874  1100  1137  1181  1241
##  [12]  1308  1398  1421  1543  1585  1664  1682  2163  2909  3006  3120
##  [23]  3188  3207  3361  3375  3442  3571  3849  3899  4047  4288  4388
##  [34]  4513  4823  4976  5028  5060  5104  5197  5287  5421  5456  5640
##  [45]  5647  5690  5691  5769  5814  5820  6131  6144  6235  6455  6501
##  [56]  6685  6829  7027  7079  7110  7306  7321  7369  7499  7778  7865
##  [67]  7866  7944  8067  8159  8276  8432  8487  9280  9429  9458  9684
##  [78]  9870  9923 10027 10045 10072 10140 10214 10437 10712 10780 11483
##  [89] 11530 11575 11669 11814 12054 12140 12306 12732 13404 13436 13449
## [100] 13544 13721 13843 14312 14485 14666 14864 15025 15206 15382 15383
## [111] 15751 15819 15995 16304 16369 16622 16634 16800 16893 16945 17126
## [122] 17163</code></pre>
<pre class="r"><code># for dogs
str_which(cats_names_tbl$animals_name_1, pattern = &quot;car&quot;)</code></pre>
<pre><code>##   [1]    53   180   271   397   449   811   874  1100  1137  1181  1241
##  [12]  1308  1398  1421  1543  1585  1664  1682  2163  2909  3006  3120
##  [23]  3188  3207  3361  3375  3442  3571  3849  3899  4047  4288  4388
##  [34]  4513  4823  4976  5028  5060  5104  5197  5287  5421  5456  5640
##  [45]  5647  5690  5691  5769  5814  5820  6131  6144  6235  6455  6501
##  [56]  6685  6829  7027  7079  7110  7306  7321  7369  7499  7778  7865
##  [67]  7866  7944  8067  8159  8276  8432  8487  9280  9429  9458  9684
##  [78]  9870  9923 10027 10045 10072 10140 10214 10437 10712 10780 11483
##  [89] 11530 11575 11669 11814 12054 12140 12306 12732 13404 13436 13449
## [100] 13544 13721 13843 14312 14485 14666 14864 15025 15206 15382 15383
## [111] 15751 15819 15995 16304 16369 16622 16634 16800 16893 16945 17126
## [122] 17163</code></pre>
<div id="rebus" class="section level2">
<h2>Rebus</h2>
<p>In the previous section, some important functions within the <code>stringr</code> ecosystem were shown. Now let’s work again with <code>stringr</code>, this time in association with the <code>rebus</code> package. This package facilitates our work when dealing with regular expressions. As a quick example, let’s imagine that we wanted to count all dogs and cats names starting with a specific letter. We just have to write <code>START %R%</code> and subsequently the required pattern:</p>
<pre class="r"><code># names that start with L
# for cats
cats_names_tbl %&gt;% 
  mutate(L_char = str_count(animals_name_1, pattern = START %R% &quot;l&quot;)) %&gt;%
  summarize(cats_words_start_with_L = sum(L_char, na.rm = TRUE))</code></pre>
<pre><code>##   cats_words_start_with_L
## 1                    1142</code></pre>
<pre class="r"><code># dogs
dogs_names_tbl %&gt;% 
  mutate(L_char = str_count(animals_name_1, pattern = START %R% &quot;l&quot;)) %&gt;%
  summarize(dogs_words_start_with_L = sum(L_char, na.rm = TRUE))</code></pre>
<pre><code>##   dogs_words_start_with_L
## 1                    2712</code></pre>
<p>In this case, we have 1142 cat first names starting with the “L” character. For dogs, we have 2712 instances.</p>
<p>Moving on with our wrangling of strings, if we would like to check the first names ending with the pattern “cy” we could simply do the following:</p>
<pre class="r"><code># find names that end with the pattern &quot;cy&quot;
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = &quot;cy&quot; %R% END
  )
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##    lucy   percy    macy  quincy   fancy  clancy   mercy   nancy   darcy 
##     104      13      10       9       6       4       3       3       2 
##   marcy chauncy   gracy    lacy  legacy   peacy   purcy  purrcy   saucy 
##       2       1       1       1       1       1       1       1       1 
##   spicy 
##       1</code></pre>
<pre class="r"><code># for dogs
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = &quot;cy&quot; %R% END
  )
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##   lucy quincy  percy   macy  darcy  fancy clancy  mercy     cy    icy 
##    358     29     16     15      7      4      3      3      2      2 
##   lacy  nancy  spicy   gacy  gancy   kacy  marcy  saucy  stacy  yancy 
##      2      2      2      1      1      1      1      1      1      1</code></pre>
<p>As we can see, we’ve included the pattern before the <code>END</code> function of <code>rebus</code> and with that we’ve indicated we wanted a pattern ending with “cy”.</p>
<p>We could simply try to find names where the third letter is a “z”. The <code>rebus</code> package facilitates our job through the <code>ANY_CHAR</code> function.</p>
<pre class="r"><code># first names where the third letter is a &quot;z&quot;
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = START %R% ANY_CHAR %R% ANY_CHAR %R% &quot;z&quot;
  )
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##       gizmo        izzy       hazel         taz        jazz       jazzy 
##          20          20          17          12          10           9 
##       lizzy       ozzie        enzo       suzie        buzz      lizzie 
##           9           9           6           6           4           4 
##      mozart        zazu       fuzzy       izzie     jezebel        liza 
##           4           4           3           3           3           3 
##       mazie        ouzo        ozzy        zuzu       dizzy        fizz 
##           3           3           3           3           2           2 
##        fuzz         jaz        kaze      kizzie         liz        orzo 
##           2           2           2           2           2           2 
##       pazzo      rizhik      tazzie      wizard       zizou        azzu 
##           2           2           2           2           2           1 
##       bazil     bazique         boz        boze        bozo         caz 
##           1           1           1           1           1           1 
##   cazadores       cazzy     cezanne      dazzle        dezi     dezmond 
##           1           1           1           1           1           1 
##         fez      fezzie      fezzik      fozzie       fozzy fuzzjackson 
##           1           1           1           1           1           1 
##    gazpacho        giza       gozer        gozo       gyzmo        haze 
##           1           1           1           1           1           1 
##    hazelnut       itzel   izzybella        jazl    jazzmine    jezavell 
##           1           1           1           1           1           1 
##    jezebell   jezebelle  jezzabelle      jezzie       kozmo       lazer 
##           1           1           1           1           1           1 
##       lazlo        lazy      lazzlo       mazel     mazinga        mazy 
##           1           1           1           1           1           1 
##       mazzy         miz        mizu         moz     muzette       muzzy 
##           1           1           1           1           1           1 
##       nazee      nozomi      puzzle     puzzles         raz        razz 
##           1           1           1           1           1           1 
##        riza      sazjha        suzi        suzy   suzykitty      tazmin 
##           1           1           1           1           1           1 
##        tazo       tazzy      tizzie         yaz        yuzu        zazi 
##           1           1           1           1           1           1 
##        zizi 
##           1</code></pre>
<p>And now the same pattern, but for dogs.</p>
<pre class="r"><code># for dogs
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = START %R% ANY_CHAR %R% ANY_CHAR %R% &quot;z&quot;
  )
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##         izzy        hazel        gizmo         enzo        ozzie 
##           60           49           46           30           25 
##       lizzie         ozzy         jazz        suzie         zuzu 
##           21           17           14           14           13 
##          taz        dozer        izzie        rizzo         suzy 
##           11           10            8            7            7 
##        jazzy         buzz       fozzie        lizzy        cozmo 
##            6            5            5            5            4 
##        dizzy       fezzik        mazey        mazie      jazmine 
##            4            4            4            4            3 
##      jezebel        lazlo         liza        mazzy       wizard 
##            3            3            3            3            3 
##        zizou        bizzy       dazzle          fez        fuzzy 
##            3            2            2            2            2 
##    izzabella         izze         izzi          jaz      jazmyne 
##            2            2            2            2            2 
##        kizzy        kozmo          liz      nizhoni         orzo 
##            2            2            2            2            2 
##       razzie         tazz       auzzie       bazely         bazi 
##            2            2            1            1            1 
##       bazzle      bezudry       bizkit       bozley        buzzy 
##            1            1            1            1            1 
##      cazaril      cezanne      cozette          dez       dizzle 
##            1            1            1            1            1 
##         elza      fizzgig          foz        fozul        fozzy 
##            1            1            1            1            1 
##         fuzz   fuzzbucket      gazelle       gizzmo        gizzy 
##            1            1            1            1            1 
##        gozer         guzi         haze     hazelnut         hazy 
##            1            1            1            1            1 
##    izzybella     jazzelle        jazzi       jazzie   jezzabelle 
##            1            1            1            1            1 
##   jezzebelle         jozy          kaz     kazanova         kazi 
##            1            1            1            1            1 
##       kazmer         kazu        kezie         kuzi   lizaminion 
##            1            1            1            1            1 
##      lizette        lizzi          luz       mazama        mazel 
##            1            1            1            1            1 
##         mazy         mizu       mizzie       mozart         moze 
##            1            1            1            1            1 
##         mozi       mozzie        mozzy        muzby         nazy 
##            1            1            1            1            1 
##        nazzy        ouzel          pez       puzzle          raz 
##            1            1            1            1            1 
##        razus   razzmatazz         rezi        rezso         rizz 
##            1            1            1            1            1 
##      rozalia        rozsa         sazi          soz         suze 
##            1            1            1            1            1 
##        suzee       suzieq       suzzie       tazman        tazzy 
##            1            1            1            1            1 
## tezcatlipoca        tizzy        tozer        tozzi         tuzi 
##            1            1            1            1            1 
##          twz      wizzard         yzzy        zazie         zazu 
##            1            1            1            1            1 
##        zezza        zizka         zozo 
##            1            1            1</code></pre>
<p>We could think about of matching a specific pattern. For instance, let’s try to find the pattern “cc”.</p>
<pre class="r"><code># match the pattern &quot;cc&quot;
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = &quot;cc&quot; %R% ANY_CHAR
    )
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##     gnocchi       rocco   chewbacca       gucci  piccadilly    staccato 
##           6           4           3           2           2           2 
##    zucchini       becca   blenducci   boudiccea      flocca      hiccup 
##           2           1           1           1           1           1 
##       kucci       lucca       lucci  macchiatto      mccone     mccovey 
##           1           1           1           1           1           1 
##    moccasin moustacchio      nicchi     piccolo     rebecca       recco 
##           1           1           1           1           1           1 
##      soccer     torocco     yacchan       zucca 
##           1           1           1           1</code></pre>
<p>“Gnocchi” seems to be the most popular cat name with the “cc” pattern.</p>
<pre class="r"><code># match the pattern &quot;cc&quot;
# for dogs
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = &quot;cc&quot; %R% ANY_CHAR
    )
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##      rocco  chewbacca      lucca      gucci      ricco    bacchus 
##         28         21         17          6          5          4 
##      bocce      zucca   boudicca      becca cappuccino   abbracci 
##          4          4          3          2          2          1 
##      bocca     chicca   chubacca    gnocchi      jacco      macca 
##          1          1          1          1          1          1 
##    macchia  macchiato      mocca      nicca      nicco      nucci 
##          1          1          1          1          1          1 
##     pucchi      pucci    puccini      ricci      rocca      rucca 
##          1          1          1          1          1          1 
##      sacco scaramucci      zacca   zaccheus 
##          1          1          1          1</code></pre>
<p>“Rocco” shows as the most popular dog name where the “cc” pattern is present.</p>
<p>Another option is to merely match more than one type of pattern. From the data exploration, some pet names were not exactly the same, though very similar. For instance, “Lucy”, “Lucie”, and “Luci”. In this case, we can use the function <code>or</code> from the <code>rebus</code> package.</p>
<pre class="r"><code># match multiple patterns with &quot;or&quot;
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = START %R% or(&quot;lucy&quot;, &quot;lucie&quot;, &quot;luci&quot;) 
    %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##  lucy  luci lucie 
##   104     3     1</code></pre>
<p>And for dogs:</p>
<pre class="r"><code># match multiple patterns with &quot;or&quot;
# for dogs
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = START %R% or(&quot;lucy&quot;, &quot;lucie&quot;, &quot;luci&quot;) 
    %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##  lucy lucie  luci 
##   358     9     7</code></pre>
<p>We could also try to find first names containing only vowels by using the <code>char_class</code> function form the <code>rebus</code> package.</p>
<pre class="r"><code># find first names that correspond only to vowels
# for cats
vow &lt;- char_class(&quot;aeiou&quot;)
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = START %R% one_or_more(vow) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##  o  e io 
##  2  1  1</code></pre>
<p>And for dogs:</p>
<pre class="r"><code># find first names that correspond only to vowels
# for dogs
vow &lt;- char_class(&quot;aeiou&quot;)
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = START %R% one_or_more(vow) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##   io iuiu    o  uau 
##    2    1    1    1</code></pre>
<p>We could also do the reverse by using the <code>negated_char_class</code> function.</p>
<pre class="r"><code># find names that do not have vowels
# for cats
not_vow &lt;- negated_char_class(&quot;aeiou&quot;)

sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = START %R% one_or_more(not_vow) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##     mr  gypsy     ms    mrs  flynn   lynx     mj    sky    dmh     dr 
##     70      9      9      8      6      6      5      5      4      4 
##     jj    nyx     bb     bc     bw     cc     dc     pj     tj     cj 
##      4      4      3      3      3      3      3      3      3      2 
##      d    dsh      g      j     jr   jynx     kt      p   rhys    sgt 
##      2      2      2      2      2      2      2      2      2      2 
##   skyy    syd     ty      1      2     30     99     bj   bryn   bynx 
##      2      2      2      1      1      1      1      1      1      1 
##    c80     dj     dw    fly  frytz    fyn   fynn     gb  glynn grrrly 
##      1      1      1      1      1      1      1      1      1      1 
##   grwh     jd     jh     jp     jt    jyn     k2     kc     kk    lbj 
##      1      1      1      1      1      1      1      1      1      1 
##      m     my   prrr    pym      q     qt     rd rhythm    ryn      s 
##      1      1      1      1      1      1      1      1      1      1 
##    sly sphynx  sydny     tk    tyr      v   whbl      z     zz 
##      1      1      1      1      1      1      1      1      1</code></pre>
<p>And for dogs:</p>
<pre class="r"><code># find names that do not have vowels
# for dogs
not_vow &lt;- negated_char_class(&quot;aeiou&quot;)

sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = START %R% one_or_more(not_vow) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##     mr  gypsy     jj     ty  flynn     pj    sky     cj     ms      z 
##     48     15     12      9      8      8      7      6      6      5 
##     bb     dj     dr   fynn     kc     mj      p     tj      b     cc 
##      4      4      4      4      4      4      4      4      3      3 
##    fry      j    nyx    sgt     bj     cy      d     gg     jp     jr 
##      3      3      3      3      2      2      2      2      2      2 
##      k     ky     lj     lt      m     pd    sly      t    tyr   wynn 
##      2      2      2      2      2      2      2      2      2      2 
##     7s    bb8     bg   bryn      c     cb     cr     dc     dw      f 
##      1      1      1      1      1      1      1      1      1      1 
##    fly     gd    grr     hy     jb     jd     jw    jwl     k2     kk 
##      1      1      1      1      1      1      1      1      1      1 
##     lb     lc lynyrd     mc  mcfly    mrs     my     pk     pm     pp 
##      1      1      1      1      1      1      1      1      1      1 
##     pt    pym   r2d2     rj    spy     sy  sylph     tt    twy    twz 
##      1      1      1      1      1      1      1      1      1      1 
##  vãlkl   yzzy 
##      1      1</code></pre>
<p>“Mr” and “Gypsy” seem to be the most popular options of first names without vowels.</p>
<p>We could also try to find names only with digits by using the function <code>one_or_more(DIGIT)</code>.</p>
<pre class="r"><code># find names only with digits
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = START %R% one_or_more(DIGIT) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##  1  2 30 99 
##  1  1  1  1</code></pre>
<p>And for dogs:</p>
<pre class="r"><code># find names only with digits
# for cats
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = START %R% one_or_more(DIGIT) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## integer(0)</code></pre>
<p>For dogs, we do not find first names with digits only.</p>
<p>Additionally, we could capture both words and digits for a given first name with the help of the function <code>capture(WRD)</code>:</p>
<pre class="r"><code># capture first name that have words and digits
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = capture(WRD) %R% one_or_more(DIGIT) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##      cat2  testcat2        30        99       c80      cat1 charlene2 
##         3         2         1         1         1         1         1 
##      deb0     jojo3        k2   number1    oscar2  slasher2   sydney2 
##         1         1         1         1         1         1         1 
##     tont2 
##         1</code></pre>
<p>“Cat2” is the most popular cat name with both words and digits.</p>
<p>Let’s see how this pattern looks for dogs:</p>
<pre class="r"><code># capture first name that have words and digits
# for cats
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = capture(WRD) %R% one_or_more(DIGIT) %R% END)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##      bb8  casper2   cayde6 jacques2       k2  number3   penny2     r2d2 
##        1        1        1        1        1        1        1        1</code></pre>
<p>There are 8 dog names with both words and digits, but none is more popular than the other.</p>
<p>Amazingly, we could easily identify first names with repeated letters. We can use the <code>REF1</code> function to try to find names with three repeated letters.</p>
<pre class="r"><code># find first names with three repeated letters
# for cats
sort(
  table(
  str_subset(
    cats_names_tbl$animals_name_1, pattern = capture(LOWER) %R% REF1 %R% REF1)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
## copurrrnicus     cosettte       grrrly     katgrrrl         prrr 
##            1            1            1            1            1 
##     purrrsia     wafffles 
##            1            1</code></pre>
<p>And for dogs:</p>
<pre class="r"><code># find first names with three repeated letters
# for cats
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = capture(LOWER) %R% REF1 %R% REF1)
)
, decreasing = TRUE)</code></pre>
<pre><code>## 
##  dollly ellliah willlow 
##       1       1       1</code></pre>
<p>We have 7 cat names with three repeated letters in a row. In dogs, we only observe this pattern 3 times.</p>
<p>To finalize, we could use the function <code>exactly</code> to detect how many times a specific pattern occurs.</p>
<pre class="r"><code># detect a pattern with exactly 
# for dogs
sort(
  table(
  str_subset(
    dogs_names_tbl$animals_name_1, pattern = exactly(&quot;lucy&quot;))
)
, decreasing = TRUE)</code></pre>
<pre><code>## lucy 
##  358</code></pre>
<p>Thus, the name “Lucy” was given to 358 dogs in Seattle in the last years.</p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>This post touched on some of the most important functions to work with strings. Hope you have enjoyed how powerful can be the <code>stringr</code> package, especially when paired together with the <code>rebus</code> package. Nonetheless, there is still much more to learn when dealing with strings. Keep learning and coding!!</p>
</div>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
                
                
                  <div class="post-footer-tags">
                    <span class="text-color-light text-small">TAGGED IN</span><br/>
                    
  <a class="tag tag--primary tag--small" href="../../../tags/stringr/">stringr</a>

  <a class="tag tag--primary tag--small" href="../../../tags/rebus/">rebus</a>

  <a class="tag tag--primary tag--small" href="../../../tags/tidytuesday/">tidytuesday</a>

                  </div>
                
              
            
            
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="../../../2019/04/euro-vs-dollar-working-with-lubridate-and-some-other-packages/" data-tooltip="Euro vs Dollar: Working with Lubridate and some other packages">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=https://toscano84.github.io/2019/04/working-with-strings-in-r-seattle-pet-names/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=https://toscano84.github.io/2019/04/working-with-strings-in-r-seattle-pet-names/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


            
              
                <div id="disqus_thread">
  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2019 Hugo Toscano. All Rights Reserved
  </span>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="4">
        
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="../../../2019/04/euro-vs-dollar-working-with-lubridate-and-some-other-packages/" data-tooltip="Euro vs Dollar: Working with Lubridate and some other packages">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=https://toscano84.github.io/2019/04/working-with-strings-in-r-seattle-pet-names/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=https://toscano84.github.io/2019/04/working-with-strings-in-r-seattle-pet-names/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="4">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Ftoscano84.github.io%2F2019%2F04%2Fworking-with-strings-in-r-seattle-pet-names%2F">
          <i class="fa fa-facebook-official"></i><span>Share on Facebook</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://twitter.com/intent/tweet?text=https%3A%2F%2Ftoscano84.github.io%2F2019%2F04%2Fworking-with-strings-in-r-seattle-pet-names%2F">
          <i class="fa fa-twitter"></i><span>Share on Twitter</span>
        </a>
      </li>
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>
    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fa fa-remove"></i>
    </div>
    
      <img id="about-card-picture" src="https://res.cloudinary.com/dabczf7ag/image/upload/v1528704790/foto1.jpg" alt="Author&#39;s picture" />
    
    <h4 id="about-card-name">Hugo Toscano</h4>
    
      <div id="about-card-bio">Contact: hugo_toscano@outlook.com</div>
    
    
    
      <div id="about-card-location">
        <i class="fa fa-map-marker"></i>
        <br/>
        Stuttgart, Germany
      </div>
    
  </div>
</div>

    <div id="algolia-search-modal" class="modal-container">
  <div class="modal">
    <div class="modal-header">
      <span class="close-button"><i class="fa fa-close"></i></span>
      <a href="https://algolia.com" target="_blank" rel="noopener" class="searchby-algolia text-color-light link-unstyled">
        <span class="searchby-algolia-text text-color-light text-small">by</span>
        <img class="searchby-algolia-logo" src="https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg">
      </a>
      <i class="search-icon fa fa-search"></i>
      <form id="algolia-search-form">
        <input type="text" id="algolia-search-input" name="search"
          class="form-control input--large search-input" placeholder="Search" />
      </form>
    </div>
    <div class="modal-body">
      <div class="no-result text-color-light text-center">no post found</div>
      <div class="results">
        
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2019/04/working-with-strings-in-r-seattle-pet-names/">
                <h3 class="media-heading">Working with Strings in R: Seattle Pet Names</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Apr 4, 2019
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Welcome to the blog. In this new post I’ll do a short tutorial on how to work with strings in R. I’ll show you some of the main functions of the stringr package and the amazing power of the rebus package. The data frame I will be using is from the week 13 of TidyTuesday. This data frame seemed to be the perfect opportunity to build this tutorial given the importance of strings for its understanding.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2019/04/euro-vs-dollar-working-with-lubridate-and-some-other-packages/">
                <h3 class="media-heading">Euro vs Dollar: Working with Lubridate and some other packages</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Apr 4, 2019
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Welcome to this new post about the Euro versus Dollar historical exchange rate since 1999 to the present day. This post will deal with dates, so I will use mainly the lubridate package and some of its most important functions. I will do my best to show you the power and simplicity of this truly magnificent tool within the R universe. Nevertheless, I won’t be restricted only to lubridate and will use some other packages to deal with this type of data.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2019/03/clustering-the-pharmaceutical-industry-stocks/">
                <h3 class="media-heading">Clustering the Pharmaceutical Industry Stocks</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Mar 3, 2019
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">In this post I will use two of the most popular clustering methods, hierarchical clustering and k-means clustering, to analyse a data frame related to the financial variables of some pharmaceutical companies. Clustering is an unsupervised learning technique where we segment the data and identify meaningful groups that have similar characteristics. In our case, the goal will be to find these groups within the pharmaceutical companies data. Like we did in the previous posts we will start by loading the required packages to our analysis.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/12/text-mining-crime-and-punishment-and-anna-karenina-a-tidytext-approach/">
                <h3 class="media-heading">Text Mining Crime and Punishment &amp; Anna Karenina: A Tidytext Approach</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Dec 12, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Welcome to a new exciting post! Today I have decided to bring you text mining applied to two of my favorite novels: Crime and Punishment by Dostoyevsky and Anna Karenina by Tolstoy. We will use mainly the incredible tidytext package developed by Julia Silge and David Robinson. You can read more about this package in the book of the same authors Text Mining with R: A Tidytext Approach.
Let us start the analysis of “Crime and Punishment” and “Anna Karenina” by loading the required packages.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/11/creating-a-model-to-increase-the-personal-loans-in-banks/">
                <h3 class="media-heading">Creating a Model to Predict if a Bank Customer accepts Personal Loans</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">In this post, we will fit a multiple logistic regression model to predict the probability of a bank customer accepting a personal loan based on multiple variables to be described later. Logistic regression is a supervised learning algorithm were the independent variable has a qualitative nature. In this case, corresponding to the acceptance or rejection of a personal loan. This tutorial will build multiple logistic regression models and assess them.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/11/german-elections-in-the-21st-century/">
                <h3 class="media-heading">German Elections in the 21st Century</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">In this blogpost, we will come back to the subject of the German Elections. We will try to show, mostly visually, the changes in election results during the 21st century. Thus, we will use data from the elections in 2002 to the last ones in 2017. The main focus will be mapping the results of the parties represented in the current Bundestag (German Parliament) during this time span. Let’s start our coding.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/10/predicting-airfares-on-new-routes/">
                <h3 class="media-heading">Predicting Airfares on New Routes a Supervised Learning Approach With Multiple Linear Regression</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Oct 10, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">This post will talk about multiple linear regression in the context of machine learning. Linear regression is one of the simplest and most used approaches for supervised learning. This tutorial will try to help you in how to use the linear regression algorithm. I am also new to the machine learning approach, but I’m very interested in this area given the predictive ability that you can gain from this. Let’s hope I can help you.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/10/hints-to-deal-with-missing-values-in-r/">
                <h3 class="media-heading">Hints to deal with Missing Values in R</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Oct 10, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">In R missing values are usually, but not always, represented by letters NA. How to deal with missing values is very important in the data analytics world. Missing data can be sometimes tricky while analyzing a data frame, since it should be handled correctly for our statistical analysis. Before diving into more complex details about missing data, the first question that should be asked in any exploratory data analysis is: Do I have missing values in my database?</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/09/combine-data-frames-in-r/">
                <h3 class="media-heading">Combine Data frames in R</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Sep 9, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Sometimes, before we start to explore our data, we need to put them together. For instance, we might have them stored in different data frames and we have to join variables from two or more data frames in one. This post will talk about the different functions we can use to achieve that goal. We will be using the dplyr package to combine different data frames.
Firstly, we will show examples related to what is called mutating joins.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="https://toscano84.github.io/2018/08/a-leaflet-approach-to-coffee-chains-starbucks-versus-dunkin-donuts/">
                <h3 class="media-heading">A Leaflet approach to Coffee Chains: Starbucks versus Dunkin&#39; Donuts</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Aug 8, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">This post talks about making interactive visualizations in R with leaflet(). In this example, I’ll map the USA locations of two of the biggest coffee chains, Starbucks and Dunkin’ Donuts. This package allows us to map data and play interactively with it. For instance, we can zoom in or zoom out to augment or diminish map details, respectively. We can add markers that signal the position of our data in the map and move the mouse cursor over to get information about it.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
      </div>
    </div>
    <div class="modal-footer">
      <p class="results-count text-medium"
         data-message-zero="no post found"
         data-message-one="1 post found"
         data-message-other="{n} posts found">
         13 posts found
      </p>
    </div>
  </div>
</div>
    
  
    
    <div id="cover" style="background-image:url('https://res.cloudinary.com/dabczf7ag/image/upload/v1533024537/cover_new2.jpg');"></div>
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="../../../js/script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js"></script>



<script>
$(document).ready(function() {
  hljs.configure({ classPrefix: '', useBR: false });
  $('pre.code-highlight > code, pre > code').each(function(i, block) {
    if (!$(this).hasClass('codeblock')) {
      $(this).addClass('codeblock');
    }
    hljs.highlightBlock(block);
  });
});
</script>


  
    
      <script>
        var disqus_config = function () {
          this.page.url = 'https:\/\/toscano84.github.io\/2019\/04\/working-with-strings-in-r-seattle-pet-names\/';
          
            this.page.identifier = '\/2019\/04\/working-with-strings-in-r-seattle-pet-names\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'toscano84';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
    
  



    
  </body>
</html>

